//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle_de_jogo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AmigoJogo
    {
        public decimal AMIGOJOGOID { get; set; }
        public decimal JOGOID { get; set; }
        public decimal AMIGOID { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime DATAEMPRESTIMO { get; set; }
    
        public virtual Amigo Amigo { get; set; }
        public virtual Jogo Jogo { get; set; }
    }
}
